[package]
name = "oxid_wasm"
version = "2020.1.0"
authors = ["Lorenzo Fontoura <lorenzo@nioel.com>"]
edition = "2018"
license = "MIT"
description = "oxid WASM rendering module"
homepage = "https://github.com/rellfy/oxid"
repository = "https://github.com/rellfy/oxid"
publish = false
